### ISSUE TITLE
Duplicación de código

### ISSUE THREAD

**Issue by lmagarin** [pabloleonalcaide/Javascript_2_Trimestre#21]
https://github.com/pabloleonalcaide/Javascript_2_Trimestre/blob/d7a7057088e7070d4162bfbdfc0ae9062e916856/mastermind%20usando%20jQuery/js/game.js#L119

Duplicas código.
 let arrayToCheck = [];     
        $circlesToFill.each(function(index,element){
              arrayToCheck.push(transformaColor(element.style.backgroundColor));
        })
return arrayToCheck;

//además, ya te comenté que podrías eliminar este problema sustituyendo los colores de mastermind(capa de negocio)

**Comment by pabloleonalcaide** [comment]
Corregido, todo el switch case se ha reducido a una línea, gracias!
